### ISSUE TITLE
"Latest Posts" not showing anything

### ISSUE THREAD

**Issue by sirrico** [eugenekolo/cozy-youth-theme#1]
After a fresh install and adding 3 posts, none show up under "latest posts".

**Comment by eugenekolo** [comment]
Hi sirrico: can you please tell me what version of Ghost you're using, and on what OS?

**Comment by sirrico** [comment]
Thank you for a quick reply!
I am using Ghost 0.8.0 on LTS 14.04 Ubuntu Server.  This is a default
configuration provided with DigitalOcean servers.  I can update to the
newest Ghost, but the server is locked at that version.

**Comment by eugenekolo** [comment]
@sirrico Have you enabled Public API? It's under "Beta Features" on the admin panel. For the latest posts to work it requires that enabled, as otherwise there's no easy way to get the list of posts from the database. That should perhaps be documented as a note.

Tested as working w/ Ghost 0.8, Ubuntu 16.04, node 4.2

**Comment by sirrico** [comment]
@eugenekolo , that seems to have fixed the issue entirely.  If this was written in the install documentation and I missed it I am terrible sorry, but thank you for helping resolve that issue.

**Comment by eugenekolo** [comment]
@sirrico awesome. i'll close the issue then.
